[package]
name = "gnstore"
version = "0.0.1"
authors = ["Peter Mezei <mezeipetister@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"
yew = "*"
lazy_static = "*"
serde = { version = "1.0", features = ["derive"] }
failure = "*"
http = "*"

[dev-dependencies]
wasm-bindgen-test = "0.2"